version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - '14:b4:03:dd:4f:69:8f:75:f3:c5:f8:25:b2:e8:f9:d8'
      - checkout
      - restore_cache:
          keys:
            - dependencies_blog
      - run: echo "A first hello"
      - run: npm -v
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_blog
      - run:
          name: Build
          command: yarn docs:build
      - run:
          name: grant authority
          # 赋予执行权限 shell chmod +x
          # 执行shell脚本
          command: chmod +x scripts/deploy.sh
      - run:
          name: deloy github
          command: ./scripts/deploy.sh
