version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - '82:4d:7e:10:67:45:37:de:72:e2:c7:13:2f:77:1c:bc'
      - checkout
      - restore_cache:
          keys:
            - dependencies_blog
      - run: echo "A first hello"
      - run: npm -v
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_blog
      - run:
          name: Build
          command: yarn docs:build
      - run:
          name: grant authority
          # 赋予执行权限 shell chmod +x
          # 执行shell脚本
          command: chmod +x scripts/deploy.sh
      - run:
          name: deloy github
          command: ./scripts/deploy.sh
